package ca.group8.gameservice.splendorgame.controller;

/**
 * Generic Action interface for blackboard architecture. Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */
public interface Action {

}
