package ca.group8.gameservice.splendorgame.controller;

import ca.group8.gameservice.splendorgame.model.Game;
import ca.group8.gameservice.splendorgame.model.PlayerReadOnly;
import ca.group8.gameservice.splendorgame.model.splendormodel.GameInfo;
import ca.group8.gameservice.splendorgame.model.splendormodel.Player;

/**
 * Generic Action interface for blackboard architecture. Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */
public class Action {
  private final Player player;
  private final GameInfo game;


  public Action(Player player, GameInfo game) {
    this.player = player;
    this.game = game;
  }

  public Player getPlayer() {
    return player;
  }

  public GameInfo getGame() {
    return game;
  }
}
