package ca.group8.gameservice.splendorgame.controller;

import ca.group8.gameservice.splendorgame.model.splendormodel.GameInfo;
import ca.group8.gameservice.splendorgame.model.splendormodel.PlayerInGame;

/**
 * Generic Action interface for blackboard architecture. Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */
public class Action {
  private final PlayerInGame playerInGame;
  private final GameInfo game;


  public Action(PlayerInGame playerInGame, GameInfo game) {
    this.playerInGame = playerInGame;
    this.game = game;
  }

  public PlayerInGame getPlayer() {
    return playerInGame;
  }

  public GameInfo getGame() {
    return game;
  }
}
