package ca.group8.gameservice.splendorgame.controller.splendorlogic;

import ca.group8.gameservice.splendorgame.model.splendormodel.Card;
import ca.group8.gameservice.splendorgame.model.splendormodel.GameInfo;
import ca.group8.gameservice.splendorgame.model.splendormodel.PlayerInGame;
import ca.group8.gameservice.splendorgame.model.splendormodel.Position;
import ca.group8.gameservice.splendorgame.model.splendormodel.TableTop;


/**
 * Generic Action abstract class for blackboard architecture.
 * Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are
 * generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */


public abstract class Action {


  abstract void execute(TableTop curTableTop, PlayerInGame playerInGame,
               SplendorActionListGenerator actionListGenerator,
               SplendorActionInterpreter actionInterpreter);

  boolean checkIsExtraAction() {return false;};

  boolean checkIsCardAction() {return false;};

  abstract Card getCurCard() throws NullPointerException;

  abstract Position getCardPosition() throws NullPointerException;
}
