package ca.group8.gameservice.splendorgame.controller.splendorlogic;

import ca.group8.gameservice.splendorgame.model.splendormodel.Card;
import ca.group8.gameservice.splendorgame.model.splendormodel.GameInfo;
import ca.group8.gameservice.splendorgame.model.splendormodel.PlayerInGame;
import ca.group8.gameservice.splendorgame.model.splendormodel.Position;


/**
 * Generic Action abstract class for blackboard architecture.
 * Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are
 * generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */


public interface Action {


  void execute(GameInfo currentGameState, PlayerInGame playerState);

  boolean checkIsCardAction();

  Card getCard();

  Position getPosition();
}
