package project.view.splendor.communication;


import io.github.isharipov.gson.adapters.JsonSubtype;
import io.github.isharipov.gson.adapters.JsonType;


/**
 * Generic Action abstract class for blackboard architecture.
 * Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are
 * generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 *
 * Every abstract class was serialized/deserialized using the repository from:
 *  * https://medium.com/@iliamsharipov_56660/handling-polymorphism-with-gson-f4a702014ffe.
 *  * Thank him so much!!!!!!!!!!!!!!!
 */


@JsonType(
        property = "type",
        subtypes = {
                @JsonSubtype(clazz = PurchaseAction.class, name = "PurchaseAction"),
                @JsonSubtype(clazz = CardExtraAction.class, name = "CardExtraAction"),
                @JsonSubtype(clazz = ClaimNobleAction.class, name = "ClaimNobleAction"),
                @JsonSubtype(clazz = PowerExtraAction.class, name = "PowerExtraAction"),
                @JsonSubtype(clazz = ReserveAction.class, name = "ReserveAction"),
                @JsonSubtype(clazz = TakeTokenAction.class, name = "TakeTokenAction"),
                @JsonSubtype(clazz = ReturnTokenAction.class, name = "ReturnTokenAction"),

        }
)
public abstract class Action {

  String type;

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }






}