package project.view.splendor.communication;

import io.github.isharipov.gson.adapters.JsonSubtype;
import io.github.isharipov.gson.adapters.JsonType;

/**
 * Generic Action abstract class for blackboard architecture. Implement your own actions, representing kinds of actions
 * performed by players in a blackboard architecture. Actions are generated by a custom ActionGenerator and performed by
 * a custom ActionInterpreter.
 */

@JsonType(
    property = "type",
    subtypes = {
        @JsonSubtype(clazz = CardAction.class, name = "cardAction"),
        @JsonSubtype(clazz = TakeTokenAction.class, name = "takeTokenAction")
    }
)

public abstract class Action {
  //Useful when the client receives the map of Actions, to identify whether action
  //is CardAction or not
  private boolean isCardAction;

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  private String type;

  public Action(boolean isCardAction) {
    this.isCardAction = isCardAction;
  }

  public boolean getIsCardAction() {
    return isCardAction;
  }

  public void setCardAction(boolean cardAction) {
    isCardAction = cardAction;
  }


  //boolean checkIsCardAction();
}